In [31]:
import numpy as np
from numpy import genfromtxt

In [32]:
data=genfromtxt('Computer-Vision-with-Python/DATA/bank_note_data.txt',delimiter=',')

In [33]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [34]:
labels=data[:,4]

In [35]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [36]:
features=data[:,0:4]

In [37]:
features


array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [38]:
X=features
y=labels

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [41]:
len(X_train)

919

In [42]:
len(X_test)

453

In [43]:
from sklearn.preprocessing import MinMaxScaler

In [44]:
scaler_object=MinMaxScaler()

In [45]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [46]:
scaled_X_train=scaler_object.transform(X_train)

In [47]:
scaled_X_test=scaler_object.transform(X_test)

In [48]:
scaled_X_train.max()

1.0000000000000002

In [49]:
from keras.models import Sequential
from keras.layers import Dense

In [50]:
model=Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))  #imput layer

model.add(Dense(8,activation='relu')) #hidden layer

model.add(Dense(1,activation='sigmoid')) #output layer


In [51]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [52]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 1s - loss: 0.6898 - acc: 0.5495
Epoch 2/50
 - 0s - loss: 0.6856 - acc: 0.5571
Epoch 3/50
 - 0s - loss: 0.6806 - acc: 0.5658
Epoch 4/50
 - 0s - loss: 0.6773 - acc: 0.5680
Epoch 5/50
 - 0s - loss: 0.6738 - acc: 0.5702
Epoch 6/50
 - 0s - loss: 0.6697 - acc: 0.5713
Epoch 7/50
 - 0s - loss: 0.6648 - acc: 0.5713
Epoch 8/50
 - 0s - loss: 0.6573 - acc: 0.5734
Epoch 9/50
 - 0s - loss: 0.6452 - acc: 0.5811
Epoch 10/50
 - 0s - loss: 0.6298 - acc: 0.6028
Epoch 11/50
 - 0s - loss: 0.6133 - acc: 0.6289
Epoch 12/50
 - 0s - loss: 0.5911 - acc: 0.6877
Epoch 13/50
 - 0s - loss: 0.5680 - acc: 0.7356
Epoch 14/50
 - 0s - loss: 0.5439 - acc: 0.7802
Epoch 15/50
 - 0s - loss: 0.5185 - acc: 0.7933
Epoch 16/50
 - 0s - loss: 0.4929 - acc: 0.8172
Epoch 17/50
 - 0s - loss: 0.4654 - acc: 0.8313
Epoch 18/50
 - 0s - loss: 0.4376 - acc: 0.8607
Epoch 19/50
 - 0s - loss: 0.4114 - acc: 0.8868
Epoch 20/50
 - 0s - loss: 0.3852 - acc: 0.9129
Epoch 21/50
 - 0s - loss: 0.3602 - acc: 0.9151
Epoch 22/50
 - 0s - lo

In [54]:
#model.predict_classes(scaled_X_test)

In [59]:
model.metrics_names

['loss', 'acc']

In [61]:
from sklearn.metrics import confusion_matrix,classification_report

In [62]:
prediction=model.predict_classes(scaled_X_test)

In [64]:
confusion_matrix(y_test,prediction)

array([[250,   7],
       [  7, 189]], dtype=int64)

In [65]:
print(classification_report(y_test,prediction))

             precision    recall  f1-score   support

        0.0       0.97      0.97      0.97       257
        1.0       0.96      0.96      0.96       196

avg / total       0.97      0.97      0.97       453



In [66]:
model.save('mysupermodel.h5')

In [67]:
from keras.models import load_model

In [69]:
newmodel=load_model('mysupermodel.h5')

In [71]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    